Made minor changes to the files
devlup-labs/gymkhana_frontend pull request #31
Opened 2020-08-23 19:38 UTC by ARKEOLOGIST

Fixed issues #28 and #29.

2020-08-25 20:55 UTC, killbotXD commented on src/components/common/Footer.vue
> +                  a(href="https://devlup-labs.github.io/#/" class="white--text" style="text-decoration: none;") Devlup Labs
Can you remove this link and add it to the `v-footer` and change `by Students' Gymkhana WebD Team` to `Devlup Labs`

2020-08-25 20:57 UTC, killbotXD requested changes
Requested a minor change

2020-08-26 06:09 UTC, ARKEOLOGIST commented
Changes have been made as requested.

2020-08-26 08:35 UTC, killbotXD commented on src/components/common/Footer.vue
> +      a(href="https://devlup-labs.github.io/#/" class="white--text" style="text-decoration: none;")
can you add `target="_blank"` in here and then I think I can merge

2020-08-26 08:46 UTC, ARKEOLOGIST commented
Done.

2020-08-26 09:30 UTC, killbotXD commented
okay LGTM

2020-08-26 09:30 UTC, killbotXD approved these changes

2020-08-26 09:31 UTC, merged